name: Push Flyer Today                

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"       

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.7"                                                           

    - name: Install dependencies                         
      run: pip install boto3 gspread google-auth pandas

    - name: Run Python script 
      env:
          READ_WRITE_TO_GSHEET_APIS_JSON: ${{ secrets.READ_WRITE_TO_GSHEET_APIS_JSON }}    
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      run: python "push_flyer_today.py"   
      
