name: Trends to Sheet               

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"       

jobs:
  trends-to-sheet:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.7"                                                           

    - name: Install dependencies                         
      run: pip install boto3 pandas duckdb google-api-python-client google-auth

    - name: Run Python script 
      env:    
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          READ_WRITE_TO_GSHEET_APIS_JSON: ${{ secrets.READ_WRITE_TO_GSHEET_APIS_JSON }}
      run: python "trends_to_sheet.py"   
      
